- shell:
    - apt install -y snapd
    - snap install rustup --classic
    - apt-get update
    - rustup override set stable
    - rustup update stable
    - apt-get install -y cmake pkg-config libfreetype6-dev libfontconfig1-dev libxcb-xfixes0-dev python3
