- shell:
    - [ apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0, Adding github cli apt repository ]
    - apt-add-repository https://cli.github.com/packages
    - apt update
    - apt upgrade -y
    - apt-get update
    - apt-get upgrade -y
    - [ apt install -y bash-completion cmake ctags file git curl build-essential snapd coreutils wget software-properties-common, Install core dependencies... ]
    - [ apt install -y scdaemon pcscd ubuntu-dev-tools gnupg, Installing GNUPG... ]
    - [ snap install node --classic --channel=8 && apt install -y yarn neovim, Installing neovim... ]
    - [ apt install -y python3 python-is-python3 && apt-get install -y python3-pip zsh, Installing zsh... ]
    - [ apt install -y fontconfig, Installing font dependencies... ]
    - [ 'if [ ! -d ~/.fzf ]; then git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf; fi && ~/.fzf/install --key-bindings --completion --no-update-rc', Installing terminal fuzzy finder (fzf)... ]
    - [ apt install -y gh, Installing github cli... ]
    - [ apt-get install -y ripgrep, Installing ripgrep... ]
    - [ apt install -y tmux ruby && gem install tmuxinator, Installing TMUX... ]
    - [ snap install docker && sudo groupadd -f docker && sudo usermod -aG docker $USER, Installing docker... ]
    - snap install scc

