- shell:
    - apt update
    - [ apt install -y build-essential curl file git, Installing Homebrew dependencies... ]
    - [ apt install -y python-is-python3, Installing zsh plugin dependencies ]
    - [ apt install -y gnome-shell-extension-autohidetopbar, Installing Gnome Hide Topbar ]

