- link:
    $HOME/Library/Fonts/MesloLGS NF Bold.ttf: fonts/MesloLGS NF Bold.ttf
    $HOME/Library/Fonts/MesloLGS NF Italic.ttf: fonts/MesloLGS NF Italic.ttf
    $HOME/Library/Fonts/MesloLGS NF Regular.ttf: fonts/MesloLGS NF Regular.ttf
    $HOME/Library/Fonts/MesloLGS NF Bold Italic.ttf: fonts/MesloLGS NF Bold Italic.ttf
