- link:
    $HOME/Library/Fonts: fonts/MesloLGS NF Bold.ttf
    $HOME/Library/Fonts: fonts/MesloLGS NF Italic.ttf
    $HOME/Library/Fonts: fonts/MesloLGS NF Regular.ttf
    $HOME/Library/Fonts: fonts/MesloLGS NF Bold Italic.ttf
