- shell:
    - [ "/bin/bash -c \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\"", Installing Homebrew ]
    - [ brew bundle --file Brewfile.mac, Install dependencies]
