- shell:
    - test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
    - test -r ~/.bash_profile && echo "test -f $(brew --prefix)/bin/brew && eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile
    - echo "test -f $(brew --prefix)/bin/brew && eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
    - [ brew bundle --file Brewfile.linux, Install dependencies ]
