- defaults:
    shell:
        stdout: true
        stderr: true
- shell:
    - [ "curl -LO https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep_11.0.2_amd64.deb", Download ripgrep ]
    - [ "sudo dpkg -i ripgrep_11.0.2_amd64.deb", Install ripgrep ]
    - [ "rm ripgrep*" ]
