- shell:
    - [ source ./configure-linuxbrew.sh && npm install -g neovim, Install neovim node client ]
    - [ source ./configure-linuxbrew.sh && pip3 install --user --upgrade pynvim, Install neovim plugin manager ]
