let mapleader = ","    " change <leader> from \ to ,

if !exists('g:vscode')
  " Plugins
  source ~/.vim/custom/plugins.vim

  " Settings
  source ~/.vim/custom/settings.vim

  " coc.nvim
  source ~/.vim/custom/coc.vim

  " Bindings
  source ~/.vim/custom/bindings.vim
else
  " VS Code
  source ~/.vim/custom/vscode.vim
endif
