# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# Some more useful shit: https://sheldon.cli.rs/Examples.html
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[templates]
defer = { value = 'zsh-defer source "{{ file }}"', each = true }

[plugins]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.oh-my-zsh]
github = 'ohmyzsh/ohmyzsh'

[plugins.shellchanges]
github = 'ohmyzsh/ohmyzsh'
dir = 'plugins'
use = ['{colored-man-pages,command-not-found,copydir,copyfile,cp,dircycle,encode64,extract,urltools,web-search}/*.plugin.zsh']

[plugins.commontools]
github = 'ohmyzsh/ohmyzsh'
dir = 'plugins'
use = ['{brew,dotnet,docker,docker-compose,flutter,gh,git,golang,mongocli,node,npm,pip,sudo,systemd,terraform,yarn}/*.plugin.zsh']

[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'
use = ['{{ name }}.zsh']

[plugins.powerlevel10k]
github = 'romkatv/powerlevel10k'
use = ['powerlevel10k.zsh-theme']

[plugins.enhancd]
github = 'b4b4r07/enhancd'

[plugins.zsh-history-substring-search]
github = 'zsh-users/zsh-history-substring-search'
apply = ['defer']

[plugins.zsh-256color]
github = 'chrissicool/zsh-256color'

[plugins.zsh-history-ltsv]
github = 'b4b4r07/zsh-history-ltsv'

[plugins.zsh-diff-so-fancy]
github = 'z-shell/zsh-diff-so-fancy'

[plugins.zsh-completions]
github = 'zsh-users/zsh-completions'

[plugins.alias-tips]
github = 'djui/alias-tips'

[plugins.zsh-autopair]
github = 'hlissner/zsh-autopair'
apply = ['defer']

# For example:
#
# [plugins.base16]
# github = "chriskempson/base16-shell"
