# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: ssh
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor: !!null vim
# Aliases allow you to create nicknames for gh commands
aliases:
    co: pr checkout
    ro: repo view --web
prompt: disabled
