# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Terraform
alias tfi="terraform init"
alias tfp="terraform plan"
alias tfa="terraform apply"
alias tfaa="terraform apply -auto-approve"
alias tfd="terraform destroy"
alias tfda="terraform destroy -auto-approve"
alias tft="terraform taint"
alias tfs="terraform show"
alias tfsl="terraform state list"
alias tfsr="terraform state remove"
alias tfr="terraform refresh"

# Arduino
alias arduino="arduino-cli"
alias sketch="arduino sketch"
alias sketchn="sketch new"

# git
alias ga="git add"
alias gaa="git add -A"
alias gb="git branch"
alias gbd="gb -D"
alias gbt="git bisect"
alias gbts="gbt start"
alias gbtb="gbt bad"
alias gbtg="gbt good"
alias gbtr="gbt reset"
alias gc="git commit"
alias gcm="git commit -m"
alias gca="git commit --amend --no-edit"
alias gco="git checkout"
alias gcob="git checkout -b"
alias gcp="git cherry-pick"
alias gcpc="git cherry-pick --continue"
alias gdf="git diff"
alias gdfc="git diff --cached"
alias gl="git log"
alias gf="git fetch"
alias gph="git push origin"
alias gphf="git push origin -f"
alias gpl="git pull origin"
alias gmg="git merge"
alias gmga="git merge --abort"
alias gmt="git mergetool"
alias gsh="git stash"
alias gsha="git stash apply"
alias gshc="git stash clear"
alias gshp="git stash pop"
alias gshl="git stash list"
alias gst="git status"
alias grb="git rebase"
alias grba="git rebase --abort"
alias grbc="git rebase --continue"
alias grbi="git rebase -i"
alias grbs="git rebase --skip"
alias grt="git reset"
alias grta="git reset ."
alias grth="git reset --hard"
alias grts="git reset --soft"


alias nr="npm run"
alias wp="nr webpack"
alias wpw="nr webwatch"
alias vimdiff="nvim -d"
alias vi="nvim"
alias vim="nvim"

unameOut="$(uname -s)"
case "${unameOut}" in
  Linux*)     machine=Linux;;
  Darwin*)    machine=Mac;;
  CYGWIN*)    machine=Cygwin;;
  MINGW*)     machine=MinGw;;
  *)          machine="UNKNOWN:${unameOut}"
esac
