# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Terraform
alias tfi="terraform init"
alias tfp="terraform plan"
alias tfa="terraform apply"
alias tfaa="terraform apply -auto-approve"
alias tfd="terraform destroy"
alias tfda="terraform destroy -auto-approve"
alias tft="terraform taint"
alias tfs="terraform show"
alias tfsl="terraform state list"
alias tfsr="terraform state remove"
alias tfr="terraform refresh"

#git
alias aa="git add -A"
alias b="git branch"
alias bd="gb -D"
alias bt="git bisect"
alias bts="gbt start"
alias btb="gbt bad"
alias btg="gbt good"
alias btr="gbt reset"
alias c="git commit"
alias cm="git commit -m"
alias ca="git commit --amend --no-edit"
alias co="git checkout"
alias cob="git checkout -b"
alias cp="git cherry-pick"
alias cpc="git cherry-pick --continue"
alias df="git diff"
alias dfc="git diff --cached"
alias gl="git log"
alias f="git fetch"
alias ph="git push origin"
alias phf="git push origin -f"
alias pl="git pull origin"
alias mg="git merge"
alias mga="git merge --abort"
alias mt="git mergetool"
alias sh="git stash"
alias sha="git stash apply"
alias shc="git stash clear"
alias shp="git stash pop"
alias shl="git stash list"
alias st="git status"
alias rb="git rebase"
alias rba="git rebase --abort"
alias rbc="git rebase --continue"
alias rbi="git rebase -i"
alias rbs="git rebase --skip"
alias rt="git reset"
alias rta="git reset ."
alias rth="git reset --hard"
alias rts="git reset --soft"


alias nr="npm run"
alias wp="nr webpack"
alias wpw="nr webwatch"
alias vimdiff="nvim -d"
alias vi="nvim"
alias vim="nvim"

unameOut="$(uname -s)"
case "${unameOut}" in
  Linux*)     machine=Linux;;
  Darwin*)    machine=Mac;;
  CYGWIN*)    machine=Cygwin;;
  MINGW*)     machine=MinGw;;
  *)          machine="UNKNOWN:${unameOut}"
esac
