# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Terraform
alias tfi="terraform init"
alias tfp="terraform plan"
alias tfa="terraform apply"
alias tfaa="terraform apply -auto-approve"
alias tfd="terraform destroy"
alias tfda="terraform destroy -auto-approve"
alias tft="terraform taint"
alias tfs="terraform show"
alias tfsl="terraform state list"
alias tfsr="terraform state remove"
alias tfr="terraform refresh"

# Arduino
alias arduino="arduino-cli"
alias sketch="arduino sketch"
alias sketchn="sketch new"

# NPM
alias nr="npm run"
alias wp="nr webpack"
alias wpw="nr webwatch"

# VIM
alias vimdiff="nvim -d"
alias vi="nvim"
alias vim="nvim"

# tmux
alias txsd="tmuxinator start default"
alias dev="tmuxinator start dev"
alias dotfiles="tmuxinator start dotfiles"

# basic
alias grep="grep --color=auto --line-number"
alias ls="ls --color=always -GF"

unameOut="$(uname -s)"
case "${unameOut}" in
  Linux*)     machine=Linux;;
  Darwin*)    machine=Mac;;
  CYGWIN*)    machine=Cygwin;;
  MINGW*)     machine=MinGw;;
  *)          machine="UNKNOWN:${unameOut}"
esac
